#!/bin/bash
###############################################################################
# This hook is to tune the ACOTSP software.
#
# PARAMETERS:
# $1 is the instance name  
# $2 is the candidate number
# The rest ($* after `shift 2') are parameters to the run of ACOTSP
#
# RETURN VALUE:
# This hook should print a single numerical value (the value to be minimized)
###############################################################################

# Path to the ACOTSP software:
EXE=../../PCDRMM_MATHEURISTICA

# What "fixed" parameters should be always passed to ACOTSP?
FIXED_PARAMS=""

# The instance name and the candidate id are the first parameters
INSTANCE=$1
CANDIDATENUM=$2

# All other parameters are the candidate parameters to be passed to ACOTSP
shift 2 || exit 1
CAND_PARAMS=$*

STDOUT="c${CANDIDATENUM}.stdout"
STDERR="c${CANDIDATENUM}.stderr"

# In case of error, we print the current time:
error() {
    echo "`TZ=UTC date`: error: $@" >&2
    exit 1
}

if [ ! -x "${EXE}" ]; then
    error "${EXE}: not found or not executable (pwd: $(pwd))"
fi
# Now we can call ACOTSP by building a command line with all parameters for it
$EXE ${FIXED_PARAMS} $INSTANCE ${CAND_PARAMS} 1> $STDOUT 2> $STDERR


# The output of the candidate $CANDIDATENUM should be written in the file 
# c${CANDIDATENUM}.stdout (see hook run for ACOTSP). Does this file exist?
if [ ! -s "${STDOUT}" ]; then
    # In this case, the file does not exist. Let's exit with a value 
    # different from 0. In this case irace will stop with an error.
    error "${STDOUT}: No such file or directory"
fi

# Ok, the file exist. It contains the whole output written by ACOTSP.
# This script should return a single numerical value, the best objective 
# value found by this run of ACOTSP. The following line is to extract
# this value from the file containing ACOTSP output.
COST=$(cat ${STDOUT} | grep -o -E 'Best [-+0-9.e]+' | cut -d ' ' -f2)
if ! [[ "$COST" =~ ^[-+0-9.e]+$ ]] ; then
    error "${STDOUT}: Output is not a number"
fi

# Print it!
echo "$COST"

# We are done with our duty. Clean files and exit with 0 (no error).
# rm -f "${STDOUT}" "${STDERR}"
exit 0
